# dtype&astype
참고 링크 : https://rfriend.tistory.com/tag/astype

방법1

In [1]:
import numpy as np

In [5]:
x = np.array([1.3, 2.6, 3.0, 4.9, 5.32], dtype=np.float64)

In [6]:
x

array([1.3 , 2.6 , 3.  , 4.9 , 5.32])

In [7]:
x.dtype

dtype('float64')

방법2

In [9]:
y = np.float64([1.3, 2.6, 3.0, 4.9, 5.32])

In [10]:
y

array([1.3 , 2.6 , 3.  , 4.9 , 5.32])

In [11]:
y.dtype

dtype('float64')

데이터 변환 방법1

In [12]:
x

array([1.3 , 2.6 , 3.  , 4.9 , 5.32])

In [13]:
x_int = x.astype(np.int64)

In [14]:
x_int

array([1, 2, 3, 4, 5], dtype=int64)

In [15]:
x_int.dtype

dtype('int64')

데이터 변환 방법2

In [16]:
y

array([1.3 , 2.6 , 3.  , 4.9 , 5.32])

In [17]:
y_int = np.int64(y)

In [18]:
y_int

array([1, 2, 3, 4, 5], dtype=int64)

In [19]:
y_int.dtype

dtype('int64')

# shape
참고 링크 : https://wikidocs.net/14606

float

In [24]:
import numpy as np

In [25]:
x = np.array((0.1,0.2,0.3))

In [26]:
x

array([0.1, 0.2, 0.3])

In [27]:
x.shape

(3,)

In [28]:
x.dtype

dtype('float64')

int

In [29]:
y = np.array(((1,2,3),(4,5,6)))

In [30]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
y.shape

(2, 3)

In [32]:
y.dtype

dtype('int32')

dtype : 소수점 안 붙였지만 float이 된다.

In [33]:
z = np.array([1,2,3],dtype='float64')

In [34]:
z

array([1., 2., 3.])

In [35]:
z.shape

(3,)

In [36]:
z.dtype

dtype('float64')

zeros

In [37]:
k = np.zeros((3,3))

In [38]:
k

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
k.shape

(3, 3)

In [40]:
k.dtype

dtype('float64')

ones

In [41]:
i = np.ones((3,3), dtype='int32')

In [42]:
i

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [43]:
i.shape

(3, 3)

In [44]:
i.dtype

dtype('int32')

empty

In [46]:
e = np.empty((3,3))

In [47]:
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
e.shape

(3, 3)

In [49]:
e.dtype

dtype('float64')

reshape

In [50]:
r = np.arange(0, 9, 1.)

In [51]:
r

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [52]:
s = np.reshape(r,(3,3))

In [53]:
s

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

만약 자기 자신을 변경하려면 shape 속성을 강제로 변경하면 된다.

In [54]:
r.shape = (3,3)

In [55]:
r

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])